spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/products/**
            - id: bff-auth
              uri: lb://bff-service
              predicates:
                - Path=/api/auth/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/turkcell-microservices
          jwk-set-uri: http://localhost:8180/realms/turkcell-microservices/protocol/openid-connect/certs

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
